((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t,n,o,s,r,i){try{var c=r(e,i),a=kt(c,"value")}catch(e){return void n(e)}kt(c,"done")?t(a):an(new dn((e=>e(a))),o,s)}function t(t){const n=function(){var n=this,o=arguments;return new dn((function(s,r){function i(t){e(a,s,r,i,c,ln,t)}function c(t){e(a,s,r,i,c,un,t)}var a=Ct(t,n,o);i(void 0)}))};return Tt(n,"apply",(function(e,t){return Ct(n,e,t)})),n}function n(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,Xn((e=>{const t=_n(_t.document)
;"interactive"==t||"complete"==t?(n&&n(),e()):Fn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),At({capture:o,once:!0}))}))}const o=["browser","chrome"],s=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=Object.getPrototypeOf,i=e=>o({__proto__:null},e),c=r(function*(){}()),a=r(Uint8Array.prototype);return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,
A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:r,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,
G_n:c.next,G_t:c.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,
S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,
X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:s(MouseEvent.prototype,"relatedTarget").get,C_d:s(CustomEvent.prototype,"detail").get,P_p:s(PageTransitionEvent.prototype,"persisted").get,
C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,FD_e:FormData.prototype.entries,TA_b:s(a,"buffer").get,TA_sa:Uint8Array.prototype.subarray,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,
decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},r="vault"in twod;if(r&&void 0===twod.vault)throw"Invalid vault"
;const i=twod.vault=twod.vault||s(twod.unsafeWindow),{cSO:c,F_c:a,F_a:d,F_b:l,F_tS:u,A_fE:p,A_so:g,A_sh:f,A_j:m,A_iO:h,A_iA:b,O_a:v,O_k:_,O_v:w,O_dP:y,O_dPy:M,O_hOP:x,O_gOPN:L,O_gOPD:E,O_gOPDs:S,O_gPO:O,O_tS:I,J_p:j,J_s:R,M_f:D,M_r:P,M_m:$,M_mi:C,N_tS:A,N_MSI:T,P_t:U,P_c:k,P_co:B,G_n:F,G_t:X,R_rABS:N,R_rAT:q,R_r:W,R_enq:H,R_cl:J,S_fCC:G,S_sl:K,S_su:Y,S_iO:z,S_sp_nr:V,S_tr:Q,S_rA_nr:Z,S_cCA:ee,S_tLC:te,S_tUC:ne,Y_tST:oe,Y_unsc:se,D_pFS:re,D_cS:ie,D_gRS:ce,D_cE:ae,D_gEBT:de,E_r:le,E_s:ue,E_rA:pe,C_pA:ge,M_d:fe,C_d:me,P_p:he,M_rT:be,U_cOU:ve,U_rOU:_e,USP_tS:we,X_o:ye,X_s:Me,X_pSD:xe,X_pSH:Le,X_pSL:Ee,X_pSO:Se,X_pSU:Oe,D_n:Ie,I_tS:je,W_aEL:Re,W_rEL:De,FD_e:Pe,TA_b:$e,TA_sa:Ce,parseInt:Ae,parseFloat:Te,console:Ue,encodeURIComponent:ke,decodeURIComponent:Be,encodeURI:Fe,decodeURI:Xe,escape:Ne,unescape:qe,atob:We,btoa:He,postMessage:Je,dispatchEvent:Ge,alert:Ke,prompt:Ye,confirm:ze,close:Ve,getElementById:Qe,createEvent:Ze,createElement:et,CustomEvent:tt,CompositionEvent:nt,KeyboardEvent:ot,MouseEvent:st,MutationObserver:rt,Uint8Array:it,FileReader:ct,DOMParser:at,XMLHttpRequest:dt,Function:lt,RegExp:ut,Blob:pt,ReadableStream:gt,Number:ft,String:mt,Proxy:ht,Window:bt}=i,vt=twod,{unsafeWindow:_t,unsafeThis:wt}=vt,yt=a,Mt=d,xt=_,Lt=w,Et=v,St=M,Ot=L,It=E,jt=O,Rt=b,Dt=P,Pt=$,$t=C,Ct=(e,t,n)=>yt(Mt,e,t,n),At=c,Tt=(e,t,n)=>(St(e,t,At({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),Ut=(e,t)=>Qt(e,t)?e[t]:void 0,kt=(e,t)=>{const n=It(e,t);return n?At(n).value:void 0},Bt=(e,t)=>{const n=(e,t,o)=>{const s=It(e,t),r=s?At(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=jt(e))?n(i,t,o):void 0};return n(e,t,5)},Ft=e=>{const t=(t,...n)=>Ct(e,t,n);return Tt(t,"wrappedJSObject",e),t},Xt=()=>e=>Ft(e),Nt=Ft(l),qt=j,Wt=Xt()(g),Ht=Xt()(f),Jt=(e,t)=>{const n=[];return Vt(e,(e=>{t(e)&&Yt(n,e)})),n},Gt=(e,t,n)=>{
const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=Pt(0,o+s));let r=void 0===n?o:n;r<0&&(r=Pt(0,o+r)),r>o&&(r=o);const i=At({});for(let t=s;t<r;t++)i[t]=kt(e,t);return Lt(i)},Kt=Xt()(m),Yt=(e,t)=>{let n=e.length||0;return Tt(e,n,t),n++,e.length=n},zt=Xt()(h),Vt=Xt()(p),Qt=Xt()(x),Zt=Xt()(V),en=Xt()(K),tn=Ft(I),nn=jt({}),on=e=>{const t=At(e),n=Ot(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o];null!==s&&"object"==typeof s&&jt(s)===nn&&(t[o]=on(s))}return t},sn=e=>{const t=Zt(tn(e)," ")
;return en(Kt(Gt(t,1)," "),0,-1)},rn=Xt()(u),cn=Xt()(A),an=Xt()(U),dn=(Xt()(k),kt(_t,"Promise")),ln=Xt()(F),un=Xt()(X),pn=Xt()(N),gn=(Xt()(q),Xt()(W)),fn=(H&&Xt()(H),J&&Xt()(J),G),mn=Xt()(Y),hn=Xt()(z),bn=(Xt()(Q),Xt()(Z||function(e,t){return Kt(Zt(this,e),t)}),Xt()(ee)),vn=Xt()(te),_n=(Xt()(ne),Ft(re),Ft(ie),Ft(ce)),wn=Ft(ae),yn=Ft(de),Mn=(Ft(le),Ft(ue),Ft(pe),Ft(be)),xn=Ft(me),Ln=Ft(he),En=fe?Xt()(fe):fe,Sn=ve,On=_e,In=(Ft(we),Ft(Pe),Ft($e)),jn=(Xt()(Ce),Xt()(ye),Xt()(Me),
Ie),Rn=tt,Dn=st,Pn=it,$n=rt,Cn=pt,An=ut,Tn=function(e,t){return kt(e,t)},Un=At({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),kn=((()=>{const e=At({getElementById:Qe,createEvent:Ze,createElement:et,dispatchEvent:Ge,addEventListener,removeEventListener}),t=At({});Vt(xt(e),(n=>{try{
const o=e[n];t[n]=function(...e){return Ct(o,_t.document,e)}}catch(e){t[n]=((e,t)=>{if(Bn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}}))})(),At({top:!0,location:!0}));twod.bridges=twod.bridges||At({});const Bn=twod.console=twod.console||At({}),Fn=At({addEventListener:Nt(Re,_t),removeEventListener:Nt(De,_t)});Vt(xt(kn),(async e=>{if(!Fn[e])try{const t=_t[e];if(null==t)return;Fn[e]=t
}catch(e){}})),Vt(xt(Un),(async e=>{if(!Fn[e])try{let t=kt(_t,e);if(void 0===t&&(wt===_t||void 0===(t=kt(wt,e))))return;const n=Un[e];Fn[e]=!1===n&&"function"==typeof t?Nt(t,wt):t}catch(e){}}));const Xn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Vt(t,(t=>t(e)))}else t=e;o=!0}}));const s=At({then:e=>(o?e(t):Yt(n,e),s)});return s},Nn=()=>cn(jn()+19831206*Dt()+1,36),qn=function(){var e=t((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}
}(),Wn=(()=>{const{console:e,bridges:t}=twod,n=At({});let o;const s=(t,o,s,i)=>{let c,a=[],d=[],l=[],u=[];const p=()=>{d=[],l=[],u=[],h(),y=null,delete n[o]},g=e=>{t.send("port.message",At({response_id:o,value:e}))},f=e=>{i&&"messageId"in e&&Yt(a,e),g(e)},m=(e,t=!0)=>{c=e,t&&g(e)},h=()=>{c=void 0},b=At({addListener:e=>{Yt(d,e)}}),v=At({addListener:e=>{Yt(l,e)}}),_=At({addListener:e=>{Yt(u,e)}}),w=()=>{p(),t.send("port.message",At({response_id:o,disconnect:!0}))};let y=At(s?{postMessage:f,
connectMessage:m,stopReconnecting:h,onMessage:b,onDisconnect:v,onReconnect:_,disconnect:w}:{postMessage:f,onMessage:b,onDisconnect:v,disconnect:w});return n[o]=At({message:t=>{if(i&&(e=>"ack"in e)(t)){const{messageId:n}=t;(t=>{if(!t)return void e.warn("PortMessaging: no message id in ack message");if(c&&c.messageId===t)return;let n=-1;Wt(a,((e,o)=>e.messageId===t&&(n=o,!0))),-1!==n?(Vt(Gt(a,0,n),(t=>e.warn(`PortMessaging: message ${t.messageId} was not ack'ed!`,t))),
a=Gt(a,n+1)):e.warn(`PortMessaging: no one is waiting for ${t}`)})(n)}d&&Vt(d,(e=>e(t)))},disconnect:()=>{if(c&&s)return r(s,o),m(c),i&&Vt(a,(e=>g(e))),void(u.length&&Vt(u,(e=>e())));l.length&&Vt(l,(e=>e())),p()}}),y},r=(e,n)=>{t.first.send("port.message",At({response_id:n,connect:!0,destination:e}))};return At({message:(t,r)=>{let i;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(r,t.response_id))}else{if(!t.response_id)throw"invalid message"
;if(!(i=n[t.response_id]))return void e.warn("ports: unknown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:function(e,n,o){const i=Nn();return r(e,i),s(t.first,i,n?e:void 0,o)},onConnect:At({addListener:e=>{o=e}})})})(),{setInterval:Hn,setTimeout:Jn,clearInterval:Gn,clearTimeout:Kn,console:Yn,cloneInto:zn,exportFunction:Vn,createObjectIn:Qn,btoa:Zn}=_t,eo=Object.assign({},Yn),to=Hn.bind(_t),no=Jn.bind(_t),oo=Gn.bind(_t),so=(Kn.bind(_t),
wt==_t.top),{arrayBuffer:ro,blob:io}=_t.Response.prototype,{arrayBuffer:co}=_t.Blob.prototype,{then:ao}=_t.Promise.prototype,{fetch:lo,location:uo,document:po,Response:go}=_t,fo=Ft(ro),mo=Ft(io),ho=Ft(co),bo=zn,vo=Vn,_o=(At({encode:e=>qe(ke(e)),decode:e=>Be(Ne(e))}),At({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=fn(255&bn(e,n));return He(t)},decode:e=>We(e)})),wo=e=>{const t=new Pn(e.length);for(let n=0;n<e.length;n++)t[n]=bn(e,n);return In(t)},yo=e=>{let t
;const n=Zt(e,","),o=Tn(n,0),s=Tn(n,1);t=-1!=hn(o,"base64")?We(s):qe(s);const r=Tn(Zt(o,":"),1),i=Tn(Zt(r,";"),0);return new Cn([wo(t)],At({type:i}))},Mo=(e,t)=>{const n=wn(_t.document,"http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Vt(xt(t),(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},xo=e=>{const t=_t.document;if(t.body||"text/xml"==t.contentType)e();else{let t=!1;const o=new $n((()=>{t=!0,xo(e),(En||(e=>e.disconnect()))(o)}))
;o.observe(_t.document,At({childList:!0})),n((()=>{t||((En||(e=>e.disconnect()))(o),e())}))}},Lo=e=>{n((()=>{no((()=>e()),1)}))};let Eo,So;const Oo=uo.host,Io=e=>{"n:"==mn(e,0,2)?Eo=mn(e,2):e&&(So=mn(e,2))},jo=()=>Eo||(So?(Eo=(e=>{const t=(e,t)=>e<<t|e>>>32-t,n=(e,t)=>{const n=2147483648&e,o=2147483648&t,s=1073741824&e,r=1073741824&t,i=(1073741823&e)+(1073741823&t);return s&r?2147483648^i^n^o:s|r?1073741824&i?3221225472^i^n^o:1073741824^i^n^o:i^n^o
},o=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&t|~e&n)(o,s,r),i),a)),n(t(e,c),o)),s=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&n|t&~n)(o,s,r),i),a)),n(t(e,c),o)),r=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e^t^n)(o,s,r),i),a)),n(t(e,c),o)),i=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>t^(e|~n))(o,s,r),i),a)),n(t(e,c),o)),c=e=>{let t,n,o="",s="";for(n=0;n<=3;n++)t=e>>>8*n&255,s="0"+cn(t,16),o+=mn(s,s.length-2,2);return o};let a,d,l,u,p,g,f,m;const h=(e=>{let t;const n=e.length,o=n+8,s=16*((o-o%64)/64+1),r=[]
;for(let e=0;e<=s-1;e++)Yt(r,0);let i=0,c=0;for(;c<n;)t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|bn(e,c)<<i,c++;return t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|128<<i,r[s-2]=n<<3,r[s-1]=n>>>29,r})(e);p=1732584193,g=4023233417,f=2562383102,m=271733878;for(let e=0;e<h.length;e+=16)a=p,d=g,l=f,u=m,p=o(p,g,f,m,h[e+0],7,3614090360),m=o(m,p,g,f,h[e+1],12,3905402710),f=o(f,m,p,g,h[e+2],17,606105819),g=o(g,f,m,p,h[e+3],22,3250441966),p=o(p,g,f,m,h[e+4],7,4118548399),m=o(m,p,g,f,h[e+5],12,1200080426),
f=o(f,m,p,g,h[e+6],17,2821735955),g=o(g,f,m,p,h[e+7],22,4249261313),p=o(p,g,f,m,h[e+8],7,1770035416),m=o(m,p,g,f,h[e+9],12,2336552879),f=o(f,m,p,g,h[e+10],17,4294925233),g=o(g,f,m,p,h[e+11],22,2304563134),p=o(p,g,f,m,h[e+12],7,1804603682),m=o(m,p,g,f,h[e+13],12,4254626195),f=o(f,m,p,g,h[e+14],17,2792965006),g=o(g,f,m,p,h[e+15],22,1236535329),p=s(p,g,f,m,h[e+1],5,4129170786),m=s(m,p,g,f,h[e+6],9,3225465664),f=s(f,m,p,g,h[e+11],14,643717713),g=s(g,f,m,p,h[e+0],20,3921069994),
p=s(p,g,f,m,h[e+5],5,3593408605),m=s(m,p,g,f,h[e+10],9,38016083),f=s(f,m,p,g,h[e+15],14,3634488961),g=s(g,f,m,p,h[e+4],20,3889429448),p=s(p,g,f,m,h[e+9],5,568446438),m=s(m,p,g,f,h[e+14],9,3275163606),f=s(f,m,p,g,h[e+3],14,4107603335),g=s(g,f,m,p,h[e+8],20,1163531501),p=s(p,g,f,m,h[e+13],5,2850285829),m=s(m,p,g,f,h[e+2],9,4243563512),f=s(f,m,p,g,h[e+7],14,1735328473),g=s(g,f,m,p,h[e+12],20,2368359562),p=r(p,g,f,m,h[e+5],4,4294588738),m=r(m,p,g,f,h[e+8],11,2272392833),
f=r(f,m,p,g,h[e+11],16,1839030562),g=r(g,f,m,p,h[e+14],23,4259657740),p=r(p,g,f,m,h[e+1],4,2763975236),m=r(m,p,g,f,h[e+4],11,1272893353),f=r(f,m,p,g,h[e+7],16,4139469664),g=r(g,f,m,p,h[e+10],23,3200236656),p=r(p,g,f,m,h[e+13],4,681279174),m=r(m,p,g,f,h[e+0],11,3936430074),f=r(f,m,p,g,h[e+3],16,3572445317),g=r(g,f,m,p,h[e+6],23,76029189),p=r(p,g,f,m,h[e+9],4,3654602809),m=r(m,p,g,f,h[e+12],11,3873151461),f=r(f,m,p,g,h[e+15],16,530742520),g=r(g,f,m,p,h[e+2],23,3299628645),
p=i(p,g,f,m,h[e+0],6,4096336452),m=i(m,p,g,f,h[e+7],10,1126891415),f=i(f,m,p,g,h[e+14],15,2878612391),g=i(g,f,m,p,h[e+5],21,4237533241),p=i(p,g,f,m,h[e+12],6,1700485571),m=i(m,p,g,f,h[e+3],10,2399980690),f=i(f,m,p,g,h[e+10],15,4293915773),g=i(g,f,m,p,h[e+1],21,2240044497),p=i(p,g,f,m,h[e+8],6,1873313359),m=i(m,p,g,f,h[e+15],10,4264355552),f=i(f,m,p,g,h[e+6],15,2734768916),g=i(g,f,m,p,h[e+13],21,1309151649),p=i(p,g,f,m,h[e+4],6,4149444226),m=i(m,p,g,f,h[e+11],10,3174756917),
f=i(f,m,p,g,h[e+2],15,718787259),g=i(g,f,m,p,h[e+9],21,3951481745),p=n(p,a),g=n(g,d),f=n(f,l),m=n(m,u);const b=c(p)+c(g)+c(f)+c(m);return vn(b)})(`${Oo}#${So}`),Eo):void 0),Ro=e=>void 0!==kt(e,"objUrl"),Do=e=>void 0!==kt(e,"blob"),Po=e=>void 0!==kt(e,"dataUri"),$o=e=>void 0!==e.binary,Co=globalThis;let Ao,To,Uo,ko,{chrome:Bo,browser:Fo}=Co;Uo=()=>{if(void 0!==Ao)return Ao;try{const e=navigator.userAgent.match(/Firefox\/([0-9]+)\./);e&&(Ao=parseInt(e[1]))}catch(e){}return Ao<78&&(Ao=78),Ao},
ko=()=>{if(void 0!==To)return To;try{To=!Bo.windows}catch(e){}return To},Uo(),Uo(),Uo(),["browser"].concat(["chrome"]);const Xo=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=No.getURL("/");return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},getInternalPageRegexp:function(){return Xo.getInternalPathRegexp(!1,".html")},
getPlatformInfo:e=>Bo.runtime.getPlatformInfo(e),getBrowserInfo:e=>Bo.runtime.getBrowserInfo(e)};let t=null;return Object.defineProperty(e,"lastError",{get:()=>Bo.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>(t=t||(Uo()<54?(location.href.match(/[^:]+:\/\/([^/]+)/)||[])[1]:Bo.runtime.id)||"FirefoxTM",t),enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>{const e=Bo.runtime.id
;return"firefox@tampermonkey.net"==e?"fire":"firefoxbeta@tampermonkey.net"==e?"firb":"fird"},enumerable:!0}),e})(),No=(()=>{const e={};let t;return Object.defineProperties({},{inIncognitoContext:{get:()=>(void 0===t&&(t=Bo.extension.inIncognitoContext),t),set:e=>{t=e},enumerable:!0},...Object.getOwnPropertyDescriptors({getURL:function(e){return Bo.runtime.getURL(e)},sendMessage:function(e,t){return Bo.runtime.sendMessage(e,t)},onMessage:{addListener:function(t){
return Bo.runtime.onMessage.addListener(((n,o,s)=>{const r="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,(e=>{const t=16*Math.random()|0;return("x"==e?t:3&t|8).toString(16)})),i=o.tab?o.tab.id:0;i&&(e[i]=e[i]||{},e[i][r]=s);let c=!0;const a=t(n,o,(t=>{c=!1,s(t),i&&delete e[i][r]}));return i&&c&&!0!==a&&delete e[i][r],a}))}},connect:function(e){return Bo.runtime.connect({name:e})},urls:{prepareForReport:function(e){return e}}})})})(),qo=()=>{(()=>{
if(/file:\/\/.*\.user\.js.*/.test(window.location.href)){const e=()=>{No.sendMessage({method:"source@firefox",source:document.body.textContent},(()=>{}))};"complete"===document.readyState?e():window.addEventListener("load",e,!1)}})()},Wo=Bo&&Bo.userScripts&&Bo.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>Bo.userScripts.onBeforeScript.addListener(e)}}:{supported:!1},Ho=({sendPrefix:e,listenPrefix:n,send:o,onMessage:s})=>{if(void 0===o||void 0===s)throw"invalid args"
;let r,i,c=1;const a=At({}),d=At({}),l=e=>{e&&(r=e)},u=e=>{const t=++c;return d[c]=e,t};s(((t,s)=>t==`${n}_${r}`?(t=>{const{m:n,r:s,a:c,n:l}=t;if(a[n]&&(Vt(a[n],(e=>e(c))),delete a[n]),"message.response"==n){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=d[e])&&(n(t),delete d[e])})(s,c)}else if(i){const t=s?t=>{o(`${e}_${r}`,At({m:"message.response",a:t,r:s}))}:()=>{};i(At({method:n,args:c,node:l}),t)}})(s):null));const p=At({init:(g=t((function*(e){r?l():l(e)})),function(e){
return g.apply(this,arguments)}),refresh:()=>null,switchId:e=>{r&&p.cleanup(),l(e)},send:(t,n,s,i)=>Xn((c=>{let a,d;"function"!=typeof s&&null!==s?(a=s,d=i):d=s,o(`${e}_${r}`,At({m:t,a:n,r:d?u(d):null,n:a})),c()})),sendToId:(t,n,s)=>{o(`${e}_${t}`,At({m:n,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),Yt(a[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var g;return p},Jo=Wo,Go=Wo.supported&&!_t.pagejs;let Ko;const Yo=(e,t)=>{try{Ko(e),t&&t()}catch(e){t&&t(e.message||e)}
},zo="u"+Nn(),{bridges:Vo}=twod;let Qo=[];const Zo=e=>{Jo.onBeforeScript.addListener((o=>{const s=(e,n)=>{Vt(t,(t=>t(e,n)))},r=e=>Yt(n,At({listener:e,clone:o.export}));St(o.global,"pagejs",At({set:o.export((t=>{delete o.global.pagejs;const n=o.metadata,{modes:i,nonce:c}=n;if(c&&Io(c),Vt(Qo,(e=>e(t,n))),Qo=[],i.js){const n=bo,i=vo,c=At({unsafeWindow:o.global,unsafeThis:o.global.window,pageWindow:o.global.window.wrappedJSObject,contextId:zo,fSend:s,fOnMessage:r,
cloneInto:n?(e,t,o)=>n(e.wrappedJSObject||e,t,o):void 0,exportFunction:i?(e,t,n)=>i(e.wrappedJSObject||e,t,n):void 0});t(o.export(c)),Vo.js.sendToId(zo,"commid",At({id:e}))}})),configurable:!0})),Ko=o.global.eval}));const t=[],n=[],o=(e,t)=>{Vt(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>Yt(t,e);return At({createBridge:()=>{const t=Ho(At({sendPrefix:"2S",listenPrefix:"2U",cloneInto:bo,send:o,onMessage:s}));return t.init(e),t}})};let es=[],ts=[];const ns=e=>{const t=No.connect(e)
;if(Xo.lastError)return;let n=[];const o=At({postMessage:e=>t.postMessage(e),onMessage:At({addListener:e=>t.onMessage.addListener(e)}),onDisconnect:At({addListener:e=>{Yt(n,e)}}),disconnect:()=>(s(!1),t.disconnect())}),s=e=>{e&&Vt(n,(e=>e())),n=[],es=Jt(es,(e=>e!==r)),ts=Jt(ts,(e=>e!==i))};t.onDisconnect.addListener((()=>s(!0)));const r=()=>{t.disconnect(),Xo.lastError,s(!0)};Yt(es,r);const i=()=>{t.disconnect(),Xo.lastError};return Yt(ts,i),o};let os,ss,rs;Fn.addEventListener("pagehide",(e=>{
Ln(e)&&Vt(ts,(e=>e()))})),Fn.addEventListener("pageshow",(e=>{Ln(e)&&Vt(es,(e=>e()))}));const{console:is}=twod,cs=e=>Xn(function(){var n=t((function*(t){const n=e.url;let o,s,r,i;if(!n)return t(At({t:e,c:o}));const c=sn(n);if("string"==typeof n){const e=mn(n,0,5);if("blob:"===e)if(rs)s=At({objUrl:At({url:n})});else{const e=yield lo(n);i=yield mo(e)}else(rs||ss)&&"data:"===e?i=yo(n):r=n}else"Blob"==c||"File"==c?i=n:"ArrayBuffer"==c&&(i=new Cn([n]));if(i)if(ss)s=At({blob:i});else if(rs){
const e=Sn(i);o=()=>On(e),s=At({objUrl:At({url:e})})}else{const e=yield(a=i,Xn((e=>{const t=new Fn.FileReader;t.onload=()=>{e(gn(t))},t.onerror=t=>{Bn.warn(`unable to decode data ${t}`),e("")},pn(t,a)}))),t=i.type||"application/octet-stream";try{s=At({dataUri:`data:${t};base64,${_o.encode(e)}`})}catch(e){is.warn(`content: failed to get blob data from ${n}`,e)}}var a;t(At({t:At({url:r,tfd:s}),c:o}))}));return function(e){return n.apply(this,arguments)}}()),as=At({setInterval:e=>{let t
;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=to(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&oo(t),t=null}))},registerMenuCommand:e=>{const t=ns("registerMenuCommand");if(!t)return void no((()=>e.disconnect()),1);let n=!1,o=!1;t.onMessage.addListener((s=>{if(n||(n=!0,o&&(t.disconnect(),o=!1)),"ack"in s)e.postMessage(s);else{const{method:t,event:n}=s;e.postMessage(At({method:t,event:n}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),
e.onMessage.addListener((e=>{const{messageId:n,name:o,uuid:s,accessKey:r,autoClose:i,title:c,id:a}=e,d=Kt([a,os,s],"#");t.postMessage(At({messageId:n,method:"registerMenuCommand",name:o,title:c,uuid:s,menuId:d,accessKey:r,autoClose:i}))})),e.onDisconnect.addListener((()=>{n?t.disconnect():o=!0}))},notification:e=>{const t=ns("notification");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},openInTab:e=>{const t=ns("openInTab");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n}=e;if("method"in e){const{method:o}=e;if("openInTab"==o)if("url"in e){let o=e.url;const{active:s,loadInBackground:r,insert:i,incognito:c,setParent:a}="boolean"==typeof e.options||void 0===e.options?At({loadInBackground:e.options
}):e.options,d=void 0===s?void 0!==r&&!r:s,l=void 0===i||i;o&&"//"==mn(o,0,2)&&(o=uo.protocol+o),t.postMessage(At({messageId:n,method:"openInTab",details:At({url:o,options:At({active:!!d,insert:!!l,incognito:!!c,setParent:!c&&!!a})}),uuid:e.uuid}))}else t.postMessage(e);else is.warn(`content: unknown method ${o}`)}else"name"in e?t.postMessage(At({messageId:n,name:e.name})):"focus"in e?t.postMessage(At({messageId:n,focus:!0})):"close"in e&&t.postMessage(At({messageId:n,close:!0}))})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},download:e=>{let t;const n=ns("download");if(!n)return void no((()=>e.disconnect()),1);let o;n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),t=!0})),e.onMessage.addListener((e=>{if("cancel"in e)t=!0,n.postMessage(At({cancel:!0,id:os,uuid:e.uuid}));else if("details"in e){const{details:s,messageId:r,uuid:i}=e;cs(s).then((({t:e,c})=>{if(t)return void(c&&c());o=c
;const{url:a,...d}=s;n.postMessage(At({messageId:r,method:"download",details:At({...d,from:e}),id:os,uuid:i,location:uo.href}))}))}else n.postMessage(At({messageId:e.messageId,method:"download",uuid:e.uuid,id:e.id}))})),e.onDisconnect.addListener((()=>{o&&o(),o=void 0,n.disconnect()}))},webRequest:e=>{const t=ns("webRequest");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,rules:o,uuid:s}=e
;t.postMessage(At({messageId:n,method:"webRequest",rules:o,uuid:s}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},xhr:e=>{let n,o;const s=[];let r;const i=function(){var e=t((function*(e){if(e&&Yt(s,e),o)yield o,i();else{const e=Ht(s);e&&e()}}));return function(t){return e.apply(this,arguments)}}(),c=ns("xhr");c?(c.onMessage.addListener((n=>{"ack"in n?e.postMessage(n):i((()=>{const{onpartial:s,data:r,...i}=n;let c;if(s&&r){const{tfd:n}=r;if(n){
const r=(e=>e&&(Do(e)||Ro(e)||Po(e)||$o(e))?(e=>{let t,n,o,s,r;if(Ro(e))t=e.objUrl.url;else if(Do(e))n=e.blob;else if(Po(e))o=e.dataUri;else{if(!$o(e))throw"incompatible TransferableData";s=e.binary,r=e.type}return At({toBlob:()=>Xn((e=>{if(n)e(n);else if(t)try{an(lo(t),(t=>{an(mo(t),(t=>{e(t)}))}))}catch(t){e(void 0)}else if(o)e(yo(o));else{if(void 0===s)throw"incompatible Transferable";{const t=wo(s);e(new Cn([t],r?At({type:r}):void 0))}}})),dispose:()=>{t&&On(t),t=n=o=s=void 0}})
})(e):void 0)(n);if(!r)return;return void(o=Xn(function(){var n=t((function*(t){const n=()=>{o=null,t(),r&&r.dispose()};try{const t=yield r.toBlob();if(!t)return void n();const o=t.type;let a;if(a="arrayBuffer"in t?yield ho(t):yield fo(new go(t)),!a)return void n();c=At({nada:At({buffer:a,type:o})}),e.postMessage(At({...i,onpartial:s,data:c})),n()}catch(e){is.warn(e),n()}}));return function(e){return n.apply(this,arguments)}}()))}c=r}else c=r;e.postMessage(At({...i,onpartial:s,data:c}))}))})),
c.onDisconnect.addListener((()=>{i(function(){var o=t((function*(){e.disconnect(),n=!0}));return function(){return o.apply(this,arguments)}}())})),e.onMessage.addListener((e=>{Go&&(e=((e,t=[])=>{const n=(e,o)=>{if(null===e)return null;if("object"==typeof e){const s=sn(e);if(-1!=zt(t,s))return e;if(o){if(-1!==zt(o,e))throw"Converting circular structure to clone";Tt(o,o.length,e)}else o=[e];if(Rt(e)){const t=[];for(let s=0;s<e.length;s++){let r;r=Qt(e,s)?Ut(e,s):Bt(e,s);const i=n(r,o);Yt(t,i)}
return o.length-=1,t}if("Object"===s){const t=At({});return Vt(xt(e),(s=>{const r=n(e[s],o);void 0!==r&&(t[s]=r)})),o.length-=1,t}throw`Unsupported type in clone: ${s}`}return e};return n(e)})(e,["Blob","File","ArrayBuffer"]));const{details:t}=e;(t?cs(t):Xn((e=>e()))).then((o=>{const{t:s,c:i}=o||At({});if(n)return void(i&&i());let a,d;r=i,s&&t?(a=At({...t,...s}),d=At({...e,details:a,location:uo.href})):d=e,c.postMessage(d)}))})),e.onDisconnect.addListener((()=>{r&&r(),r=void 0,c.disconnect()
}))):no((()=>e.disconnect()),1)},onurlchange:e=>{const t=ns("onurlchange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},onaudiostatechange:e=>{const t=ns("onaudiostatechange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},values:e=>{const t=ns("values");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},backgroundControl:e=>{const t=ns("backgroundControl");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),
t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)},keepAlive:e=>{const t=ns("keepAlive");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e),Xo.lastError})),e.onDisconnect.addListener((()=>{t.disconnect()}))):no((()=>e.disconnect()),1)}}),ds=At({
setTimeout:({args:e,cb:t})=>{no(t,e.t)},setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const c=i||("html"==r?"text/html":"text/plain");_t.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(c,n)}),At({capture:!0,once:!0})),_t.document.execCommand("copy"),t()},closeTab:({args:{uuid:e},cb:t})=>{
No.sendMessage(At({method:"closeTab",uuid:e,id:os}),(e=>{e&&e.error&&is.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{No.sendMessage(At({method:"focusTab",uuid:e,id:os}),(e=>{e&&e.error&&is.warn(e.error),t(e)}))},navigateTab:({args:{uuid:e,url:t,location:n},cb:o})=>{No.sendMessage(At({method:"navigateTab",uuid:e,url:t,location:n,id:os}),(e=>{e&&e.error&&is.warn(e.error),o(e)}))},addElement:(ls=t((function*({args:e,node:t,cb:o}){try{const s=Mo(e.tag,At({...e.properties||At({}),
...e.id?At({id:e.id}):At({})}));let r,i;if("script"===e.tag&&(r=jo())&&s.setAttribute("nonce",r),t)i=t;else{const e=_t.document;if(i=e.head||e.body||e.documentElement,!i){const e=_t.document;i=yield Xn((t=>n((()=>t(e.head||e.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){is.warn("content: error adding script",e)}})),function(){return ls.apply(this,arguments)}),tabs:({args:e,cb:t})=>{e.method="tabs",No.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{
e.method="cookie",No.sendMessage(e,(e=>e&&t(e.data)))},audio:({args:e,cb:t})=>{e.method="audio",No.sendMessage(e,(e=>e&&t(e.data)))}});var ls;const us=At({init:()=>{os=twod.contextId},setup:(e,t)=>{ss=e,rs=t},processMessage:({method:e,args:t,node:n},o)=>{let s;if(s=ds[e])return s(At({args:t,node:n,cb:o}));is.warn(`content: unknown method ${e}`),o()},processConnect:(e,t)=>{let n;if(n=as[e])return n(t)}
}),ps=["GM_info","GM.info"],gs=["unsafeWindow","navigate",...ps],fs=e=>e.replace(new RegExp("[\"']","g"),"\\$1");let ms=!1;const hs=(e,n,o,s,r,i)=>{const{console:c}=twod;ms=ms||e.logLevel>=60;const{version:a,injectMode:d,inIncognitoContext:l,isFirstPartyIsolation:u,downloadMode:p,relaxedCsp:g,userAgent:f,container:m,logLevel:h}=e,b=At({version:a,injectMode:d,inIncognitoContext:l,isFirstPartyIsolation:u,downloadMode:p,relaxedCsp:g,container:m});Vt(n,function(){var n=t((function*(t){
const{script:n,storage:a}=t,{name:d,uuid:l,options:{run_at:u}}=n,{requires:p,...g}=n,m=p.length,v=!n.options.unwrap,_=At({...b,userAgent:f,logLevel:h,sandboxMode:r});let w,y;const M=((e,t)=>{const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:c}=t,{name:a,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e="";const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none")
;let g;return g=u?ps:d.concat(gs),g.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),l.push(`p.${n}`))})),
[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${fs(a)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",fs(a),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,c,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,c,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return v?(w=()=>{ms&&c.debug(`env: inject "${d}" now`);const e=`__f__${Nn()}`,t=At({storage:a,script:g}),n=`window["${e}"] = function(){${M}}`;let r=!0;s.once(`scriptack-${e}`,(()=>{ms&&!r&&c.log(`env: execution of "${d}" was delayed`),o(n,(e=>{e&&c.error(`Uncaught SyntaxError: ${e}`)}))})),s.send("script",At({id:e,unwrap:!1,bundle:t,flags:_})),r=!1},y="context-menu"==u||"document-start"==u?void 0:()=>{
ms&&c.debug(`env: run "${d}" now  (${m} requires)`),s.send("run",At({uuid:l}))}):y=()=>{ms&&c.debug(`env: inject @unwrap "${d}" now`),o(M,(e=>{e&&c.error(`Uncaught SyntaxError: ${e}`)}))},i&&(yield null),bs(d,u,w,y,ms)}));return function(e){return n.apply(this,arguments)}}())},bs=(e,t,o,s,r)=>{const{console:i}=twod;let c;"document-start"==t?(r&&i.debug(`env: run "${e}" ASAP -> document-start`),c=e=>e()):"document-body"==t?(r&&i.debug(`env: schedule "${e}" for document-body`),
c=xo):"context-menu"==t?r&&i.debug(`env: run "${e}" ASAP -> context-menu`):"document-end"==t?(r&&i.debug(`env: schedule "${e}" for document-end`),c=e=>n(!1,e)):(r&&i.debug(`env: schedule "${e}" for document-idle`),c=Lo),o&&o(),s&&c&&c((()=>{s()}))},vs=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},_s=({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const s=e=>o?o(e,_t.document):e,i=At({});let c,a,d=1;const l=At({});let u=!1,p=[];const g=()=>{
_=_t.document.documentElement,u=!1;const e=p;p=[],Vt(e,(e=>{u||y()?Yt(p,e):e()}))};let f;const m=e=>{const t=++d;return l[d]=e,t},h=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:c,c:a}=((e,t,n)=>{let o,r;return n?(r=new Dn(e,At({relatedTarget:n})),o=new Rn(e,At({detail:s(t)}))):o=new Rn(e,At({detail:s(t)})),At({m:r,c:o})})(e,At({m:n,a:o,r}),i);c&&Ct(Ge,_t,[c]),Ct(Ge,_t,[a])},b=t=>{const n=(e=>{if("MouseEvent"===sn(e)){const t=Mn(e);if(!t)throw"Invalid MouseEvent";return void(f=t)}const t=on(xn(e))
;return f&&(t.n=f,f=void 0),t})(t);if(!n)return;const{m:o,r:s,a:r,n:d}=n;if(i[o]&&(Vt(i[o],(e=>e(r))),delete i[o]),"unlock"==o)h(`${e}_${a}`,At({m:"unlocked",a:void 0,r:null})),g();else if("unlocked"==o)g();else if("message.response"==o){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(s,r)}else if(c){const t=s?t=>{h(`${e}_${a}`,At({m:"message.response",a:t,r:s}))}:()=>{};c(At({method:o,args:r,node:d}),t)}},v=e=>{e&&(a=e),a&&Fn.addEventListener(`${n}_${a}`,b,!0)
};let _,w;const y=()=>{if((()=>{const e=_t.document.documentElement;return _||(_=e),_!==e})()){if(w){const e=w;w=void 0,e(_t.document)}return!0}},M=e=>(_=_t.document.documentElement,Xn(function(){var n=t((function*(t){if(w=t,r&&!e&&(yield null,y()))return;const n=new $n((()=>{y()&&n.disconnect()}));n.observe(_t.document,At({childList:!0}))}));return function(e){return n.apply(this,arguments)}}())),x=At({init:(L=t((function*(t,n){a?v():v(t),M(n).then((()=>{u=!0,x.refresh(),h(`${e}_${a}`,At({
m:"unlock",a:void 0,r:null}))}))})),function(e,t){return L.apply(this,arguments)}),refresh:()=>{const e=a;e&&(x.cleanup(),x.init(e,!0))},switchId:e=>{a&&x.cleanup(),v(e)},send:(t,n,o,s)=>Xn((r=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=s):c=o,y();const d=()=>{h(`${e}_${a}`,At({m:t,a:n,r:c?m(c):null,n:i})),r()};u?Yt(p,d):d()})),sendToId:(t,n,o)=>{h(`${e}_${t}`,At({m:n,a:o,r:null}))},setMessageListener:e=>{c=e},once:(e,t)=>{i[e]||(i[e]=[]),Yt(i[e],t)},cleanup:()=>{
a&&(Fn.removeEventListener(`${n}_${a}`,b,!0),a=void 0)}});var L;return x},ws=function(e,t,n,o,s){let r;const i=jo(),c=Mo("script");i&&c.setAttribute("nonce",i);try{c.textContent=t,e.appendChild(c)}catch(e){r=e.message||e}if(i&&c.removeAttribute("nonce"),!s){const e=c.parentNode;e&&e.removeChild(c)}return o&&o(r),!r},ys=(e,t)=>{try{ws(po.head||po.body||po.documentElement||po,e,0,t)}catch(e){t&&t(e.message||e)}};let Ms,xs;const Ls=e=>{const t=ns("tabInfo");t?(t.onMessage.addListener((e=>{
if("ack"in e);else{const{info:t}=e;t?Ms=on(t):eo.warn("tabInfo: unexpected message",e)}})),t.onDisconnect.addListener((()=>{Es()})),e(t)):no((()=>Ls(e)),100)},Es=()=>{Ls((e=>{Ms=xs||Ms,xs=void 0,e.postMessage(At({method:"tabInfo",messageId:Nn(),info:Ms}))}))},Ss=e=>{e=e||Fn.location.href;const t=ns("tabInfo");t?(t.onMessage.addListener((e=>{"ack"in e||eo.warn("tabInfo.frame: unexpected message",e)})),t.onDisconnect.addListener((()=>{Ss(e)})),t.postMessage(At({method:"tabInfo",messageId:Nn(),
url:e}))):no((()=>Ss(e)),100)};let Os=!1;const Is=location.pathname+location.search,js="TM_"+Xo.short_id+window.btoa(Is.length+Is).substr(0,255).replace(/[#=/]/g,"_"),Rs=()=>{let e,t,n,o;try{o=document.cookie.split(";")}catch(e){return}for(e=0;e<o.length;e++)if(t=o[e].substr(0,o[e].indexOf("=")),n=o[e].substr(o[e].indexOf("=")+1),t=t.replace(/^\s+|\s+$/g,""),0===t.indexOf(js)){document.cookie=t+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;";const e=Be(n);if(0!==e.indexOf("blob:"))continue;let o
;try{if(0!==(new URL(e).origin+"/").indexOf(No.getURL("/")))continue;if(o=new XMLHttpRequest,o.open("GET",e,!1),o.send(null),200===o.status||0===o.status)return JSON.parse(o.responseText)}catch(e){console.warn("content: unable to decode "+(o&&o.responseText||"unknown"))}}};let Ds=!1;const Ps=(e,t,o)=>{const{contextId:s,bridges:r,console:i}=twod;let c;Xn((n=>{const o=e=>{let t=1;const o=()=>{Os&&i.log('content: send "prepare" message'),No.sendMessage({method:"prepare",id:s,topframe:so,
url:window.location.href},(s=>{if(!Ds){if(!s)return Os&&i.log("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(o,t),void(t=$t(2*t,3e3));Ds=!0,s.nonce&&Io(s.nonce),xt(s.contexters).length||xt(s.scripts).length||s.external_connect?(e&&e(s),n({info:s,type:"complete"==_n(_t.document)?"late":"normal"})):n({info:s})}}))};!function(e){const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())}
;t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}(o)},r=()=>{let r;if(Os&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",wt.tm_info),(r=wt.tm_info)||(r=Rs())){delete wt.tm_info,r.nonce&&Io(r.nonce);const{contexters:o,scripts:i}=r;if(xt(o).length||xt(i).length){if(r.contexters.raw||r.scripts.raw)if(e.raw)void 0===c&&(c=e.raw());else if(!t)throw"raw inject missing";n({info:r,type:"sync"})}else n({info:r});{let e;No.sendMessage({
method:"prepare",id:s,topframe:so,url:window.location.href,scripts:e,cleanup:!0},(()=>null))}}else t?o((({scripts:t,contexters:n})=>{e.raw&&void 0===c&&(t.raw||n.raw)&&(c=e.raw())})):(e.raw&&void 0===c&&(c=e.raw()),o())};t?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:d})=>{const{external_connect:l}=a;if(!t&&(e=>{if(e){const t=location.href.split("#")[0];return e.some((({source:e,flags:n})=>{const o=new An(e,n);if(""===t.replace(o,""))return!0}))}return!1
})(l)&&qn((()=>r.first.send("external.connect"))),d){Os=Os||a.logLevel>=60;const{scripts:l,sharedBlobs:p,sharedObjectUrls:g}=a;if(us.setup(p,g),l.raw){let n;if(t&&!e.raw||!c)n=!0;else{let e=!1;const t=r.raw,o=Nn();t.once("ack",(()=>{e=!0})),t.once("injectableack",(()=>{ys(`window["${o}"] = 1`)})),t.send("injectable",{id:o}),n=!e}n&&(e.js?(l.js=(l.js||[]).concat(l.raw||[]),delete l.raw):e.dom&&(l.dom=(l.dom||[]).concat(l.raw||[]),delete l.raw))}if(l.js){if(!e.js)throw"js inject missing";e.js()}
if(l.dom){if(!e.dom)throw"dom inject missing";e.dom()}n(!1,(()=>{Os&&i.log("content: DOMContentLoaded"),Vt(xt(r),(e=>r[e].send("DOMContentLoaded")))})),u=()=>{Os&&i.log("content: load"),Vt(xt(r),(e=>r[e].send("load")))},"complete"==_n(_t.document)?u():Fn.addEventListener("load",(()=>u()),At({capture:!0,once:!0}));const f=(l.dom||[]).length+(l.js||[]).length+(l.raw||[]).length;Os&&i.log("content: "+(d||"normal")+" start event processing for "+s+" ("+f+" to run)"),$s(a,"sync"===d),
!so&&f&&Ss(location.href),o()}else o();var u}))},$s=(e,t)=>{const{bridges:n}=twod,{scripts:s,...r}=e;s.js&&hs(r,s.js,Yo,n.js,"js",t),s.dom&&(Vt(o,(e=>wt[e]=void 0)),hs(r,s.dom,vs,n.dom,"dom",t)),s.raw&&hs(r,s.raw,ys,n.raw,"raw",t)},Cs=function(){var e=t((function*(){const{contextId:e}=twod,{location:t,document:o}=_t;(yield Xn((e=>n((()=>e(o.body||o)))))).addEventListener("mouseenter",(()=>{try{No.sendMessage(At({method:"contextmenu",url:t.href,id:e}),(()=>{}))}catch(e){}}),!1)}))
;return function(){return e.apply(this,arguments)}}();let As;t((function*(){const{unsafeWindow:e,bridges:t}=twod,{location:n,document:o}=e,r=o instanceof XMLDocument;if(!At({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return;so&&(Es(),Fn.addEventListener("pagehide",(e=>{Ln(e)&&(xs=Ms)})));const i=twod.contextId?twod.contextId:twod.contextId=Nn();let c;const a=At({});Et(twod.console,eo),Xn((n=>{if(Go){const{createBridge:e}=Zo(i);o=(o,s)=>{As=c=o;const{modes:i}=s;i.js&&(t.js=e(),
a.js=()=>!1,r&&(i.raw=!1)),n(s)},Yt(Qo,o)}else Xn((t=>{As=c=e.pagejs,delete e.pagejs,As?t():(()=>{let e=n=>{delete _t.pagejs,e=void 0,(e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";As=c=e,t()})(n)};St(_t,"pagejs",At({set:e,configurable:!0})),no((()=>{e&&e()}),1)})()})).then((()=>{n(At({modes:At({js:!1,raw:!0,dom:!0})}))}));var o})).then((({modes:{dom:o,raw:d},answer:l})=>{var u;if(qo(),l&&(u=l).scripts&&u.contexters&&(wt.tm_info=l),o){
const e=Go?vs(`() => ${c};`)():c,{createBridge:n,inject:o}=((e,t)=>{const n=(e,t)=>{Vt(s,(n=>n(e,t)))},o=e=>Yt(r,At({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{Vt(r,(({listener:n,clone:o})=>n(e,o(t))))},c=e=>Yt(s,e),a="c"+Nn();let d;return At({createBridge:()=>(d=Ho(At({sendPrefix:"2S",listenPrefix:"2U",send:i,onMessage:c})),d.init(e),d),inject:()=>(t(At({unsafeWindow:_t,unsafeThis:wt,pageWindow:_t.wrappedJSObject,contextId:a,fSend:n,fOnMessage:o})),d.sendToId(a,"commid",At({id:e})),!0)})
})(i,e);a.dom=o,t.dom=n()}if(d){const{createBridge:e,inject:n}=((e,t)=>{let n;return At({createBridge:()=>(n=_s(At({sendPrefix:"2P",listenPrefix:"2C",cloneInto:bo})),n),inject:()=>{n.init(e);let o=!1;const r=Nn(),i="("+rn(((e,t)=>{const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,enumerable:!1,writable:!1,configurable:!0}))}))+')("'+r+'", '+rn(s)+")";return n.once("ack",(()=>{o=!0})),(o=>{((e,t)=>{const n=Tn(yn(_t.document,"*"),0)||_t.document,o=Mo("div"),s=o.attachShadow(At({
mode:"closed"}));s.appendChild(Mo("style",":host { display: none }"));const r=Mo("iframe",At({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return;i=null;let n=!1;try{const t=r.contentDocument,o=r.contentWindow;t&&o&&(n=ws(Tn(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,At({once:!0,capture:!0})),s.appendChild(r),n.appendChild(o),i&&i()})(o,((o,s)=>{
ws(o,`((w, g) => {(${t})({ unsafeWindow: typeof g === "undefined" ? w : g, unsafeThis: w, vault: ${s?`w["${r}"]`:"null"}, contextId: "${r}", __proto__: null }); delete w["${r}"]; })(window, globalThis)\n`,0,(()=>{n.sendToId(r,"commid",At({id:e}))}),!0)}))})(i),o}})})(i,c);a.raw=n,t.raw=e()}const p=t.first=t.js||t.raw||t.dom;No.onMessage.addListener(((t,o,s)=>{"executeScript"==t.method?(t.url&&0!==hn(n.href,t.url)||void 0!==t.topframe&&t.topframe!=so||$s(t.info,!1),
s(At({}))):so&&("loadUrl"==t.method?(e.location=t.url,s(At({}))):"reload"==t.method?(n.reload(),s(At({}))):"setForeignAttr"==t.method?(p.send(t.method,t),s(At({}))):eo.log("content: unknown method "+(e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const s=typeof e;if("object"===s){if(n){if(-1!=zt(n,e))throw"Converting circular structure to JSON";Tt(n,n.length,e)}else n=[e];if(Rt(e)){let s="";for(let o=0;o<e.length;o++){let r;r=Qt(e,o)?Ut(e,o):Bt(e,o);const i=t(r,n)
;s+=`${o?",":""}${void 0===i?"null":i}`}o=`[${s}]`}else{let s="";Vt(xt(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${R(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===s)throw"Do not know how to serialize a BigInt";o=R(e)}}return o};return t(e)})(t)))})),Wn.onConnect.addListener(((e,t)=>{us.processConnect(e,t)})),us.init(),Vt(xt(t),(e=>{if("first"==e)return;const n=t[e];n.setMessageListener(((t,o)=>{const{method:s,args:r}=t
;if("port.message"==s)Wn.message(r,n);else if("csp"==s){let t;t="raw"==e?ys:"dom"==e?vs:Yo,t(r.src,(e=>{e&&eo.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)No.sendMessage(At({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=Tn(e,0),n=Tn(e,1),o=eo[t]||eo.log;o&&Ct(o,eo,((e,...t)=>{let n=e.length;const o=At(e);for(let e=0;e<t.length;e++){const s=t[e],r=Rt(s)?s:[s];for(let e=0;e<r.length;e++)o[n+e]=kt(r,e);n+=r.length}return Lt(o)
})(["injected:"],(e=>{const t=[];return Vt(e,(e=>{Yt(t,(e=>"string"==typeof e?qt(e):e)(e))})),t})(n)))}else"commid"==s||(e=>"ack"==e.method||"injectableack"==e.method||0===hn(e.method,"scriptack-"))(t)||us.processMessage(t,o)}))})),Ps(a,r,(()=>As=void 0)),Cs()}))}))()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_0d8zcr")